### ISSUE TITLE
unable to composer require the updated version

### ISSUE THREAD

**Issue by VinylVault** [AnssiAhola/php-discogs-api#1]
sadly the `ricbra` merge failed, I'm trying to re-do the same project (same one we worked on in python) in Laravel, (as another learning project) is there a way I can install this updated version?

**Comment by AnssiAhola** [comment]
Oh hey @VinylVault !

Theres actually a fork from this one that can be installed from packagist via `composer require`
Repo: https://github.com/calliostro/php-discogs-api
Packagist: https://packagist.org/packages/calliostro/php-discogs-api

But if you really want to include this one then put this in your composer.json
```json
"repositories": [{
	"type": "path",
	"url": "path/to/local/clone"
}],
"require": {
	"ricbra/php-discogs-api": "dev-master"
}
```

This will try to install the ricbra package but the repositories path overrides it.
https://getcomposer.org/doc/05-repositories.md#path
